brew cask install iterm2
brew cask insstall slack
brew cask install google-japanese-ime
brew cask install sourcetree
brew cask install skitch
brew cask install adobe-reader
brew cask install charles
brew cask install docker
brew cask install google-chrome
brew cask install mamp
brew cask install skype
brew cask install virtualbox
brew cask install betterzipql
brew cask install choosy
brew cask install filezilla
brew cask install iconjar
brew cask install mapture
brew cask install qlmarkdown
brew cask install quicklook-json
brew cask install sourcetree
brew cask install visual-studio-code
brew cask install brave
brew cask install coteditor
brew cask install firefox
brew cask install java
brew cask install qlcolorcode
brew cask install qlstephen
brew cask install rambox
brew cask install taskr
brew cask install xmind
brew cask install zoomus
brew cask install sequel-pro
brew cask install toggl
